version: '3.7'

services: 
  pgsql:
    restart: always
    image: quay.io/rhysallister/elephant
    ports:
      - "55559:55559"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    command: -p 55559 
             -c skltn.api_user=${SKLTN_API_USER} 
             -c skltn.api_password=${SKLTN_API_PASSWORD}
             -c skltn.jwt_secret="${SKLTN_JWT_SECRET}"
             -c skltn.arb_var_1=${SKLTN_ARBITRARY_VARIABLE_1}
             -c skltn.arb_var_2=${SKLTN_ARBITRARY_VARIABLE_2}
             -c skltn.arb_var_3=${SKLTN_ARBITRARY_VARIABLE_3}
    volumes:
      # - "./pgdata:/var/lib/postgresql/data"
      # - "./sql:/sql"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
  pgrst:
    restart: always
    image: postgrest/postgrest
    ports:
      - "55558:55558"
    environment:
      PGRST_DB_URI: postgres://skltn:_dot_skltn@pgsql:55559/skltn
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: everyman 
      PGRST_SERVER_PORT: 55558
      PGRST_JWT_SECRET: ${SKLTN_JWT_SECRET}
    depends_on:
      - pgsql
  swggr:
    restart: always
    image: swaggerapi/swagger-ui
    ports:
      - "55557:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:55558/
    depends_on:
      - pgrst 
  
